### ISSUE TITLE
maximum memory for current TBTOOLS: While using the "visualize the NCBI cdd pattern"

### ISSUE THREAD

**Issue by Winlover10** [CJ-Chen/TBtools-II#56]
问题已解决。

**Comment by CJ-Chen** [comment]
实在是非常抱歉！由于我个人时间精力确实有限，为良好兼顾工作与家庭，对于「TBtools」软件的使用问题确实无法抽出时间精力回复。非我本意，但确实无法一一回复（希望理解，目前TBtools有~200,000用户，遇到问题非常正常）。
作为个人，我确实无法一方面确保软件正常且持续开发和维护，另一方面做使用答疑。因此我将后者几乎完全剥离，写了一个推文《一分钟入门并精通TBtools使用》，相信可以解决您的问题。
https://www.yuque.com/cjchen/hirv8i/iclxpx2841g205hm
请注意，「TBtools技能易物群」是一个由其他团队代理运营，但可以解决你所有 TBtools 使用问题的社群，我个人推荐您加入。        
            
                
                    
                            
                                
                            
                            
                                120509419
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- Replied Message ----FromAnson ***@***.***>Date1/22/2024 ***@***.***>***@***.***>Subject[CJ-Chen/TBtools-II] maximum memory for current TBTOOLS: While using the "visualize the NCBI cdd pattern" (Issue #56)陈老师好：我试图可视化95条序列的cdd 结果时，出现了以下报错，想请问一下解决方案，日志以附件形式上传。
I encountered the following error while attempting to visualize the CDD results for 95 sequences.  I kindly request guidance on a solution.. The log is attached for reference.Best regards.
TBtools.7530699826108086973.20240122171851.log—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
