### ISSUE TITLE
Could not create awt.dll file

### ISSUE THREAD

**Issue by MonsterLaplace** [CJ-Chen/TBtools-II#58]
![image](https://github.com/CJ-Chen/TBtools-II/assets/104540426/29771c8b-7221-459f-bea4-7eab8fccf1d1)
Can not update the TBtools to the latest version in my Windows 11 PC due to the question in the above picture. Could you have some suggestions to help me solving this problem Thank you.

**Comment by CJ-Chen** [comment]
try the latestjdk version&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 29, 2024 17:35 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [CJ-Chen/TBtools-II] Could not create awt.dll file (Issue #58)




 
image.png (view on web)
 Can not update the TBtools to the latest version in my Windows 11 PC due to the question in the above picture. Could you have some suggestions to help me solving this problem Thank you.

**Comment by MonsterLaplace** [comment]
> try the latestjdk version&nbsp;
> 
> 
> 
> ---Original---
> From: ***@***.***&gt;
> Date: Mon, Jan 29, 2024 17:35 PM
> To: ***@***.***&gt;;
> Cc: ***@***.***&gt;;
> Subject: [CJ-Chen/TBtools-II] Could not create awt.dll file (Issue #58)
> 
> 
> 
> 
>  
> image.png (view on web)
>  Can not update the TBtools to the latest version in my Windows 11 PC due to the question in the above picture. Could you have some suggestions to help me solving this problem Thank you.
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Problem solved, Thank you!
