### ISSUE TITLE
RAR to zip/tar

### ISSUE THREAD

**Issue by zeakey** [CJ-Chen/TBtools-II#59]
RAR is almost a 中国特色 file format.

Better to use zip or tar that are more compatible.

**Comment by xizhesun** [comment]
> RAR is almost a 中国特色 file format.
> 
> Better to use zip or tar that are more compatible.

Please change your wrong idea！ The RAR format is widely used  around the world. Even Windows OS has natively supported the RAR format. 

If you can't use the RAR format, you should first ask yourself whether you're really suit for bioinformatic works, instead of making additional demands on the developers! The Chinese tradition tells us to handle problems we could solve by ourself without troubling others!  Is that the 特色 of your country which would like to bother others with things you can handle on your own???? 

<img width="694" alt="image" src="https://github.com/CJ-Chen/TBtools-II/assets/4266961/edcb9867-f8ac-46d2-8eb2-461ce7207d52">

**Comment by zeakey** [comment]
I was looking at the screenshot in your readme.
![image](https://github.com/CJ-Chen/TBtools-II/assets/6763078/459eb362-efe8-4bc9-9eba-f6389099c992)
